import { db } from "@/lib/firebase";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Clock } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";

export default async function SharePage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;

  // Query Firestore for a document where shareId == id
  const snapshot = await db.collection("user_history").where("shareId", "==", id).limit(1).get();

  if (snapshot.empty) {
    notFound();
  }

  const doc = snapshot.docs[0].data();

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto">
        
        <div className="flex justify-between items-end mb-8 border-b border-gray-200 pb-5">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 tracking-tight" style={{ fontFamily: 'var(--font-outfit)' }}>
              Shared Script
            </h1>
            <p className="text-gray-500 mt-2 text-sm">Generated by RISER AI Copilot</p>
          </div>
          <Link href="/" className="text-sm font-medium text-[#4a3aff] hover:text-[#3b2de0] transition-colors">
            Try RISER AI &rarr;
          </Link>
        </div>

        <div className="bg-white rounded-3xl shadow-sm border border-gray-100 overflow-hidden">
          {/* Header */}
          <div className="p-8 border-b border-gray-100 bg-gray-50/50">
            <div className="flex justify-between items-start mb-5">
              <span className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-[#f4f3ff] text-[#4a3aff] text-xs font-bold uppercase tracking-wider">
                {doc.category}
              </span>
              <span className="flex items-center text-sm font-medium text-gray-400 gap-1.5">
                <Clock className="w-4 h-4" />
                {doc.createdAt?.toDate ? doc.createdAt.toDate().toLocaleDateString() : new Date(doc.createdAt).toLocaleDateString()}
              </span>
            </div>
            <h2 className="text-xl font-semibold text-gray-900 leading-snug">
              "{doc.query}"
            </h2>
          </div>
          
          {/* Body */}
          <div className="p-8 text-gray-800 text-base leading-relaxed custom-scrollbar [&_code]:bg-gray-100 [&_code]:text-gray-800 [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:rounded [&_code]:font-mono [&_pre]:bg-gray-900 [&_pre]:text-gray-100 [&_pre]:p-4 [&_pre]:rounded-xl [&_pre_code]:bg-transparent [&_pre_code]:text-inherit [&_pre_code]:p-0 [&_p]:mb-5 [&_h2]:text-2xl [&_h2]:font-bold [&_h2]:mb-3 [&_h2]:mt-8 [&_h3]:text-xl [&_h3]:font-bold [&_h3]:mb-3 [&_h3]:mt-6 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:mb-5 [&_ul_li]:mb-2 [&_ol]:list-decimal [&_ol]:pl-5 [&_ol]:mb-5 [&_ol_li]:mb-2">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {doc.response}
            </ReactMarkdown>
          </div>
        </div>

      </div>
    </div>
  );
}
