"use client";

import { useState, useRef } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Clock, Star, Share2, Check, Download } from "lucide-react";
import { useReactToPrint } from "react-to-print";

// Extracted Card Component to isolate the print reference
function VaultCard({ item, toggleFavorite, handleShare, sharingId, copiedId }: any) {
  const contentRef = useRef<HTMLDivElement>(null);
  const handlePrint = useReactToPrint({
    contentRef: contentRef,
    documentTitle: `RISER_Export_${new Date().toISOString().split('T')[0]}`,
  });

  return (
    <div className="bg-white rounded-2xl border border-gray-100 shadow-sm hover:shadow-md transition-shadow overflow-hidden flex flex-col h-[400px]">
      {/* Header */}
      <div className="p-5 border-b border-gray-50 bg-gray-50/50 flex-shrink-0">
        <div className="flex justify-between items-start mb-3">
          <span className="inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-[#f4f3ff] text-[#4a3aff] text-xs font-bold uppercase tracking-wider">
            {item.category}
          </span>
          <div className="flex items-center gap-2">
            <span className="flex items-center text-xs font-medium text-gray-400 gap-1 mr-1">
              <Clock className="w-3.5 h-3.5" />
              {new Date(item.createdAt).toLocaleDateString()}
            </span>
            
            <button 
              onClick={() => handlePrint()}
              title="Export as PDF"
              className="transition-colors p-1.5 rounded-full hover:bg-gray-200 cursor-pointer text-gray-400 hover:text-gray-700"
            >
              <Download className="w-4 h-4" />
            </button>

            <button 
              onClick={() => handleShare(item.id)}
              disabled={sharingId === item.id}
              title="Copy Share Link"
              className="transition-colors p-1.5 rounded-full hover:bg-gray-200 cursor-pointer text-gray-400 hover:text-gray-700 disabled:opacity-50"
            >
              {copiedId === item.id ? <Check className="w-4 h-4 text-green-500" /> : <Share2 className="w-4 h-4" />}
            </button>

            <button 
              onClick={() => toggleFavorite(item.id, item.isFavorite)}
              title="Toggle Favorite"
              className={`transition-colors p-1.5 rounded-full hover:bg-gray-200 cursor-pointer ${item.isFavorite ? 'text-yellow-400' : 'text-gray-300'}`}
            >
              <Star className="w-4 h-4" fill={item.isFavorite ? "currentColor" : "none"} />
            </button>
          </div>
        </div>
        <h3 className="font-semibold text-gray-900 text-sm line-clamp-2" title={item.query}>
          "{item.query}"
        </h3>
      </div>
      
      {/* Body (Markdown Content) */}
      <div className="p-5 overflow-y-auto flex-1 relative custom-scrollbar">
        <div className="text-gray-700 text-sm [&_code]:bg-gray-100 [&_code]:text-gray-800 [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:rounded [&_code]:font-mono [&_pre_code]:bg-transparent [&_pre_code]:text-inherit [&_pre_code]:p-0 [&_p]:mb-3 [&_h2]:text-lg [&_h2]:font-bold [&_h2]:mb-2 [&_h3]:text-md [&_h3]:font-bold [&_h3]:mb-2 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:mb-3 [&_ol]:list-decimal [&_ol]:pl-5 [&_ol]:mb-3">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {item.response}
          </ReactMarkdown>
        </div>
      </div>

      {/* Hidden Printable Content */}
      <div className="hidden">
        <div ref={contentRef} className="p-10 bg-white">
          <div className="mb-8 border-b pb-4">
            <h1 className="text-2xl font-bold text-gray-900 mb-2">"{item.query}"</h1>
            <p className="text-sm text-gray-500">Generated by RISER AI on {new Date(item.createdAt).toLocaleDateString()}</p>
          </div>
          <div className="text-black text-base leading-relaxed [&_code]:bg-gray-100 [&_code]:text-gray-800 [&_code]:px-1.5 [&_code]:py-0.5 [&_code]:rounded [&_code]:font-mono [&_pre_code]:bg-transparent [&_pre_code]:text-inherit [&_pre_code]:p-0 [&_p]:mb-4 [&_h2]:text-xl [&_h2]:font-bold [&_h2]:mb-3 [&_h2]:mt-6 [&_h3]:text-lg [&_h3]:font-bold [&_h3]:mb-2 [&_h3]:mt-4 [&_ul]:list-disc [&_ul]:pl-5 [&_ul]:mb-4 [&_ol]:list-decimal [&_ol]:pl-5 [&_ol]:mb-4">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {item.response}
            </ReactMarkdown>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function VaultView({ initialItems }: { initialItems: any[] }) {
  const [items, setItems] = useState(initialItems);
  const [activeTab, setActiveTab] = useState<"all" | "favorites">("all");
  const [sharingId, setSharingId] = useState<string | null>(null);
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const handleShare = async (id: string) => {
    setSharingId(id);
    try {
      const res = await fetch("/api/vault/share", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id })
      });
      const data = await res.json();
      if (data.shareId) {
        const url = `${window.location.origin}/share/${data.shareId}`;
        await navigator.clipboard.writeText(url);
        setCopiedId(id);
        setTimeout(() => setCopiedId(null), 2000);
      }
    } catch (e) {
      console.error("Failed to share", e);
    } finally {
      setSharingId(null);
    }
  };

  const toggleFavorite = async (id: string, currentStatus: boolean) => {
    // Optimistic update
    setItems(items.map(item => item.id === id ? { ...item, isFavorite: !currentStatus } : item));

    try {
      const res = await fetch("/api/vault/favorite", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id, isFavorite: !currentStatus })
      });
      if (!res.ok) throw new Error("Failed to update");
    } catch (e) {
      // Revert on failure
      setItems(items.map(item => item.id === id ? { ...item, isFavorite: currentStatus } : item));
    }
  };

  const displayedItems = activeTab === "favorites" ? items.filter(i => i.isFavorite) : items;

  return (
    <div>
      {/* Tabs */}
      <div className="flex space-x-4 mb-8">
        <button 
          onClick={() => setActiveTab("all")}
          className={`px-5 py-2.5 text-sm font-semibold rounded-full transition-colors shadow-sm ${activeTab === "all" ? "bg-[#4a3aff] text-white" : "bg-white text-gray-600 hover:bg-gray-50 border border-gray-200"}`}
        >
          All Scripts
        </button>
        <button 
          onClick={() => setActiveTab("favorites")}
          className={`px-5 py-2.5 text-sm font-semibold rounded-full transition-colors shadow-sm flex items-center gap-1.5 ${activeTab === "favorites" ? "bg-[#4a3aff] text-white" : "bg-white text-gray-600 hover:bg-gray-50 border border-gray-200"}`}
        >
          <Star className="w-4 h-4" />
          Favorites
        </button>
      </div>

      {displayedItems.length === 0 ? (
         <div className="bg-white rounded-2xl p-12 text-center border border-gray-100 shadow-sm">
            <h3 className="text-lg font-medium text-gray-900">No items found</h3>
            <p className="text-gray-500 mt-2">
              {activeTab === "favorites" ? "You haven't favorited any scripts yet. Click the star icon on any script to save it to your Swipe File!" : "Generate some ideas using the AI Copilot!"}
            </p>
          </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
          {displayedItems.map((item: any) => (
             <VaultCard 
               key={item.id} 
               item={item} 
               toggleFavorite={toggleFavorite} 
               handleShare={handleShare} 
               sharingId={sharingId} 
               copiedId={copiedId} 
             />
          ))}
        </div>
      )}
    </div>
  );
}
